# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKppsI5X3VTgZkiZC9a6mz-PQLVFW_yG
"""

import numpy as np

list1=[2,4,6,8,10]
for i in list1:
        print(i**2)

for i in list1:
    print(i**3)

def square(list1):
    return[i*2 for i in list1]

square(list1)

def cube(list1):
    return[i**3 for i in list1]

cube(list1)

